// styles/AppStyles.ts
import { Platform, StyleSheet } from "react-native";
import { colors, width } from "../constants/AppConstants";

export const styles = StyleSheet.create({
  // Hero Section Styles
  heroBackground: {
    height: 280,
    justifyContent: "center",
    alignItems: "center",
  },
  heroImage: {
    opacity: 0.8,
  },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  heroContent: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  heroTextContainer: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 20,
    padding: 24,
    backdropFilter: "blur(10px)",
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: colors.textWhite,
    textAlign: "center",
    marginBottom: 8,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  heroSubtitle: {
    fontSize: 18,
    color: colors.textWhite,
    textAlign: "center",
    opacity: 0.9,
    marginBottom: 12,
  },
  heroDivider: {
    width: 60,
    height: 3,
    backgroundColor: colors.accentLight,
    borderRadius: 2,
    marginBottom: 12,
  },
  heroDescription: {
    fontSize: 14,
    color: colors.textWhite,
    textAlign: "center",
    opacity: 0.8,
    lineHeight: 20,
  },

  // Main Container
  container: {
    flex: 1,
    backgroundColor: colors.cardBackground,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  containerWithHomeButton: {
    paddingBottom: 100, // Extra space for home button
  },

  // Mode Section
  modeSection: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 16,
    textAlign: "center",
  },
  modeRow: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "center",
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.cardBackground,
    alignItems: "center",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  modeBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    transform: [{ scale: 1.02 }],
  },
  modeText: {
    fontWeight: "700",
    color: colors.textPrimary,
    fontSize: 14,
    textAlign: "center",
  },
  modeTextActive: { color: colors.textWhite },
  modeDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: 4,
    opacity: 0.8,
  },
  modeDescriptionActive: {
    color: colors.textWhite,
    opacity: 0.9,
  },
  noModeText: {
    marginTop: 16,
    color: colors.textSecondary,
    fontSize: 16,
    textAlign: "center",
    fontStyle: "italic",
  },

  // Form Styles
  form: {
    width: "100%",
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    color: colors.primary,
    textAlign: "center",
  },

  label: {
    marginTop: 16,
    marginBottom: 8,
    color: colors.textPrimary,
    fontWeight: "600",
    fontSize: 16,
  },
  input: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    backgroundColor: colors.inputBg,
    borderColor: colors.border,
    fontSize: 16,
    color: colors.textPrimary,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },

  datePickerButton: {
    justifyContent: "center",
    backgroundColor: colors.inputBg,
  },
  dateText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "500",
  },

  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
    marginBottom: 20,
    justifyContent: "center",
  },
  chip: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.chipBg,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
    transform: [{ scale: 1.05 }],
  },
  chipText: {
    color: colors.chipText,
    fontWeight: "600",
    fontSize: 14,
  },
  chipTextActive: { color: colors.textWhite },

  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 32,
    marginBottom: 20,
  },

  btn: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  btnPrimary: {
    backgroundColor: colors.primary,
  },
  btnDisabled: { backgroundColor: colors.disabled },
  btnSecondary: {
    backgroundColor: colors.cardBackground,
    borderWidth: 2,
    borderColor: colors.border,
  },
  btnTextPrimary: {
    color: colors.textWhite,
    fontWeight: "bold",
    fontSize: 16,
  },
  btnTextSecondary: {
    color: colors.textPrimary,
    fontWeight: "600",
    fontSize: 16,
  },

  // Tracker Styles
  trackerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    gap: 12,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
  },
  dropdownBtn: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  trackerBtnRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  searchBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },

  // Results Section
  resultsSection: {
    marginTop: 24,
  },
  loadingContainer: {
    alignItems: "center",
    padding: 40,
  },
  loadingText: {
    marginTop: 12,
    color: colors.textSecondary,
    fontSize: 16,
  },
  emptyState: {
    alignItems: "center",
    padding: 40,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.textSecondary,
    marginTop: 16,
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: colors.textLight,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 20,
  },
  resultsHeader: {
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  resultsCount: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
  },

  closeButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    alignSelf: "center",
    minWidth: 120,
  },

  // Premium Result Cards
  resultCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  resultType: {
    fontWeight: "800",
    color: colors.primary,
    fontSize: 16,
    marginBottom: 4,
  },
  resultLine: {
    marginTop: 8,
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 22,
  },
  resultBold: {
    fontWeight: "700",
    color: colors.textPrimary,
  },

  // Premium Modal Styles
  modalContainer: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  modalHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.textPrimary,
  },
  modalCloseBtn: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: colors.chipBg,
  },
  modalContent: {
    flex: 1,
  },
  modalLoading: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  modalLoadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.textSecondary,
  },
  modalEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  modalEmptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.textSecondary,
    marginTop: 16,
    textAlign: "center",
  },
  modalEmptySubtext: {
    fontSize: 14,
    color: colors.textLight,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 20,
  },
  suggestionsList: {
    flex: 1,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.cardBackground,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  suggestionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  suggestionText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.textPrimary,
  },

  // IMPRESSIVE SUCCESS POPUP STYLES
  successOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  successPopup: {
    width: width * 0.85,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 25,
    elevation: 15,
  },
  successGradient: {
    paddingVertical: 40,
    paddingHorizontal: 30,
    alignItems: "center",
    position: "relative",
  },
  confettiContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
  },
  confettiPiece: {
    position: "absolute",
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  successContent: {
    alignItems: "center",
    zIndex: 1,
  },
  checkmarkContainer: {
    marginBottom: 20,
  },
  checkmarkCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.textWhite,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.textWhite,
    textAlign: "center",
    marginBottom: 12,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  successSubtitle: {
    fontSize: 16,
    color: colors.textWhite,
    textAlign: "center",
    opacity: 0.9,
    lineHeight: 22,
    marginBottom: 24,
  },
  successDivider: {
    width: 60,
    height: 3,
    backgroundColor: colors.textWhite,
    borderRadius: 2,
    marginBottom: 20,
    opacity: 0.8,
  },
  successBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  successBadgeText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.success,
  },

  // STUNNING HOME BUTTON FOOTER STYLES
  homeFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 34 : 16, // Account for safe area
    backgroundColor: "transparent",
    borderTopWidth: 0,
    alignItems: "center",
  },
  homeButtonGradient: {
    borderRadius: 25,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  homeButton: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  homeButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  homeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.3)",
    position: "relative",
  },
  homeIconGlow: {
    position: "absolute",
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    top: -2,
    left: -2,
  },
  homeButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.textWhite,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  homeButtonPulse: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  sparklesContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 25,
    overflow: "hidden",
  },
  sparkle: {
    position: "absolute",
  },
});
